
import { ShoppingCategory } from './types';

export const EXPENSE_CATEGORIES = [
  'Housing & Utilities',
  'Food & Daily Needs',
  'Transport & Travel',
  'Health & Personal Care',
  'Fun & Lifestyle',
  'Miscellaneous'
];

// Colors based on brand palette: #3EAFD2, #FF9800, #7E57C2, #4CAF50, #F06292, #AB47BC, #757575
export const SHOPPING_CATEGORY_COLORS: Record<ShoppingCategory, string> = {
  [ShoppingCategory.SUPERMARKET]: 'border-l-[#3EAFD2]',
  [ShoppingCategory.WET_MARKET]: 'border-l-[#4CAF50]',
  [ShoppingCategory.OTHERS]: 'border-l-[#757575]',
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: 'Chinese Simplified' },
  { code: 'zh-TW', name: 'Chinese Traditional' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ko', name: 'Korean' },
  { code: 'ja', name: 'Japanese' },
];

// The source of truth for UI strings.
export const BASE_TRANSLATIONS: Record<string, string> = {
  // Dashboard
  'dashboard.greeting.morning': 'Good morning',
  'dashboard.greeting.afternoon': 'Good afternoon',
  'dashboard.greeting.evening': 'Good evening',
  'dashboard.family_board': 'Family Board',
  'dashboard.tap_to_pin': 'Tap to pin a note...',
  'dashboard.type_note': 'Type a note for the family...',
  'dashboard.shopping': 'Shopping',
  'dashboard.items_needed': 'Items needed',
  'dashboard.tasks': 'Tasks',
  'dashboard.todo': 'To-Do',
  'dashboard.meals': 'Meals',
  'dashboard.planned': 'Planned',
  'dashboard.expenses': 'Expenses',
  'dashboard.this_month': 'This Month',
  'dashboard.up_next': 'Up Next',
  'dashboard.view_schedule': 'View Schedule',
  'dashboard.everyone': 'Everyone',
  'dashboard.eating': 'eating',
  'dashboard.language': 'Language',

  // Filters & Common Tabs
  'filter.all': 'All',
  'filter.today': 'Today',
  'filter.overdue': 'Overdue',
  'filter.later': 'Later',
  'filter.general': 'General',

  // Shopping
  'shopping.title': 'Shopping List',
  'shopping.new_item': 'New Item',
  'shopping.item_name': 'Item Name',
  'shopping.unit_placeholder': 'Unit (pkt, kg)',
  'shopping.quick_add': 'Quick Add',
  'shopping.completed': 'Completed',
  'shopping.clear_all': 'Clear All',
  'shopping.no_items': 'No items in list',
  'category.supermarket': 'Supermarket',
  'category.wet_market': 'Wet Market',
  'category.others': 'Others',

  // Tasks
  'tasks.title': 'Tasks',
  'tasks.new_task': 'New Task',
  'tasks.task_name': 'Task Name',
  'tasks.assignees': 'Assignees',
  'tasks.recurrence': 'Does not repeat',
  'tasks.custom_recurrence': 'Custom Recurrence',
  'tasks.repeat_every': 'Repeat every',
  'tasks.repeat_on': 'Repeat on',
  'tasks.ends': 'Ends',
  'tasks.never': 'Never',
  'tasks.on': 'On',
  'tasks.after': 'After',
  'tasks.occurrences': 'occurrences',
  'tasks.once': 'Once',
  'tasks.daily': 'Daily',
  'tasks.weekly': 'Weekly',
  'tasks.monthly': 'Monthly',
  'tasks.yearly': 'Yearly',
  
  // Tasks Empty States
  'tasks.no_tasks_all': 'No tasks created',
  'tasks.no_tasks_today': 'No tasks due today',
  'tasks.no_tasks_overdue': 'No overdue tasks',
  'tasks.no_tasks_later': 'No upcoming tasks',

  // Day Bubbles (Single Letter)
  'day.letter.sun': 'S',
  'day.letter.mon': 'M',
  'day.letter.tue': 'T',
  'day.letter.wed': 'W',
  'day.letter.thu': 'T',
  'day.letter.fri': 'F',
  'day.letter.sat': 'S',
  
  // Day Short (For Recurrence)
  'day.short.sun': 'Sun',
  'day.short.mon': 'Mon',
  'day.short.tue': 'Tue',
  'day.short.wed': 'Wed',
  'day.short.thu': 'Thu',
  'day.short.fri': 'Fri',
  'day.short.sat': 'Sat',

  // Meals
  'meals.title': 'Meals',
  'meals.day_view': 'Day View',
  'meals.week_view': 'Week View',
  'meals.today': 'Today',
  'meals.back_to_week': 'Back to Current Week',
  'meals.plan_meal': 'Plan meal...',
  'meals.add_dish': 'Add dish',
  'meals.the_dish': 'The Dish',
  'meals.whats_for': 'What\'s for',
  'meals.who_eating': 'Who is eating?',
  'meals.add_meal': 'Add Meal',
  'meals.save_changes': 'Save Changes',
  'meals.suggest_ai': 'Suggest with AI',
  'meals.group_all': 'All',
  'meals.group_adults': 'Adults',
  'meals.group_kids': 'Kids',
  'meals.view_day': 'Day',
  'meals.view_week': 'Week',

  // Meal Types
  'meal.type.breakfast': 'Breakfast',
  'meal.type.lunch': 'Lunch',
  'meal.type.dinner': 'Dinner',
  'meal.type.snacks': 'Snacks',

  // Meal Audience
  'meals.audience_label': 'This meal is for',
  'meals.audience_all': 'Everyone',
  'meals.audience_adults': 'Adults',
  'meals.audience_kids': 'Kids',

  // Meal RSVP
  'meals.join': 'Join Meal',
  'meals.im_in': "I'm In",
  'meals.im_out': "I'm Out",
  'meals.leave': 'Leave',
  'meals.eating': 'Eating',
  'meals.ill_be_eating': "I'll be eating",
  'meals.no_dish_yet': 'No dish yet',
  'meals.not_for_you': 'Not for you',
  'meals.no_one_yet': 'No one yet',
  'meals.plan_dish': 'Plan Dish',
  'meals.edit_dish': 'Edit dish',
  'meals.add_meal_plan': 'Add Meal Plan',
  'meals.adults_only': 'Adults Only',
  'meals.kids_only': 'Kids Only',
  'meals.tap_to_join': 'Tap to Join',
  'meals.joined': 'Joined',

  // Expenses
  'expenses.title': 'Expenses',
  'expenses.total_month': 'Total this month',
  'expenses.scan_receipt': 'Scan Receipt',
  'expenses.analyzing': 'Analyzing Receipt with AI...',
  'expenses.breakdown': 'Spending Breakdown',

  // Household Info
  'info.title': 'Household Info',
  'info.add_section': 'Add Custom Section',
  'info.edit_info': 'Edit Info',
  'info.new_info': 'New Info',
  'info.category': 'Category',
  'info.title_label': 'Title',
  'info.content_label': 'Content',
  'info.cat.house_rules': 'House Rules',
  'info.placeholder.category': 'General',
  'info.placeholder.title': 'e.g. WiFi Password',
  'info.placeholder.content': 'Enter details...',

  // Profile
  'profile.title': 'Family Profiles',
  'profile.back': 'Back',
  'profile.add_member': 'Add Family Member',
  'profile.edit_profile': 'Edit Profile',
  'profile.logout': 'Log Out',
  'profile.allergies': 'Allergies & Medical',
  'profile.preferences': 'Preferences',
  'profile.none_added': 'None added',
  'profile.change_photo': 'Change Photo',
  'profile.take_photo': 'Take Photo',
  'profile.choose_library': 'Choose from Library',
  'profile.invite_link': 'Invite Link',
  'profile.copy_link': 'Copy Link',
  'profile.copied': 'Copied!',
  'profile.restart_tutorial': 'Restart Tutorial',

  // Onboarding
  'onboarding.welcome': 'Welcome, {name}!',
  'onboarding.step1.desc': 'Let\'s get your home set up. Click \'Got it\' to go to your profile and add your family members.',
  'onboarding.step2.title': 'Grow your Family',
  'onboarding.step2.desc': 'Tap the + button to add your family members.',
  'onboarding.skip': 'Skip',
  'onboarding.got_it': 'Got it',
  'onboarding.add_member': 'Add Family Member',

  // ToDo (unified Shopping + Tasks)
  'todo.title': 'To Do',
  'todo.shopping': 'Shopping',
  'todo.tasks': 'Tasks',
  'todo.suggested': 'Suggested',
  'todo.completed': 'Completed',
  'todo.no_shopping': 'No shopping items yet',
  'todo.no_tasks': 'No tasks yet',
  'todo.add_hint': 'Press Enter to add / tap (+) to set details',
  'todo.category.home_care': 'Home Care',
  'todo.category.family_care': 'Family Care',
  'todo.category.others': 'Others',

  // Nav
  'nav.home': 'Home',
  'nav.todo': 'To Do',
  'nav.meals': 'Meals',
  'nav.cost': 'Expenses',
  'nav.info': 'Info',
  'nav.profile': 'Profile',
  
  // Common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.add': 'Add',
  'common.remove': 'Remove',
  'common.confirm_clear': 'Are you sure you want to clear these items?',
  'common.close': 'Close',
  'common.edit': 'Edit',
  'common.update': 'Update',
  'common.view': 'View',
  'common.start': 'Start',
  'common.all': 'All',
  'common.none': 'None',
  'common.none_listed': 'None listed',
  'common.more': 'more',
  'common.qty': 'Qty',
  'common.unit_pcs': 'pcs',
  'common.unit_kg': 'kg',
  'common.unit_l': 'L',
  'common.eg': 'e.g.',
  'common.eg_milk': 'e.g., Milk',
  'common.eg_clean_bathroom': 'e.g., Clean bathroom',
  'common.eg_wifi_password': 'e.g. WiFi Password',
  'common.where_did_you_spend': 'Where did you spend?',
  'common.store_name': 'Store name',
  'common.enter_details': 'Enter details...',
  'common.add_with_details': 'Add with details',
  'common.sort_by': 'Sort by',
  'common.show_only_mine': 'Show only mine',
  'common.added_date': 'Added Date',
  'common.due_date': 'Due Date',
  'common.newest': 'newest',
  'common.oldest': 'oldest',
  'common.list': 'List',
  'common.summary': 'Summary',
  'common.all_expenses': 'All Expenses',
  'common.total_for_all': 'Total for all expenses',
  'common.total_for_month': 'Total for',
  'common.joined': 'Joined',
  'common.tap_to_join': 'Tap to Join',
  'common.add_allergy': 'Add allergy',
  'common.add_preference': 'Add preference',
  'common.allergy_medical': 'Allergy & Medical',
  'common.settings': 'Settings',
  'common.plan': 'Plan',
  'common.security': 'Security',
  'common.payment': 'Payment',
  'common.free': 'Free',
  'common.core': 'Core',
  'common.pro': 'Pro',
  'common.monthly': 'Monthly',
  'common.yearly': 'Yearly',
  'common.mo': 'mo',
  'common.yr': 'yr',
  'common.essential_info': 'Essential Info',
  'common.training': 'Training',
  'common.home': 'Home',
  'common.school': 'School',
  'common.doctor': 'Doctor',
  'common.hospital': 'Hospital',
  'common.shops': 'Shops',
  'common.others': 'Others',
  'common.house_rules': 'House Rules',
  'common.routine': 'Routine',
  'common.cleaning': 'Cleaning',
  'common.general': 'General',
  'common.category': 'Category',
  'common.title': 'Title',
  'common.content': 'Content',
  'common.does_not_repeat': 'Does not repeat',
  'common.show': 'Show',
  'common.item_name': 'Item Name',
  'common.task_name': 'Task Name',
  'common.unit': 'Unit',
  'common.unit_placeholder': 'pcs, kg, L...',
  'common.added_date_newest': 'Added Date (newest)',
  'common.added_date_oldest': 'Added Date (oldest)',
  'common.due_date_newest': 'Due Date (newest)',
  'common.due_date_oldest': 'Due Date (oldest)',
  'common.my_items_only': 'My Items Only',
  'common.clear_filters': 'Clear Filters',
  'common.reset_to_default': 'Reset to Default',
  'common.name': 'Name',
  'common.enter_name': 'Enter name',
  'common.current_plan': 'Current Plan',
  'common.price': 'Price',
  'common.popular': 'Popular',
  'common.change_plan': 'Change Plan',
  'common.choose_your_plan': 'Choose Your Plan',
  'common.processing': 'Processing...',
  'common.cancel_subscription': 'Cancel Subscription',
  'common.expires_on': 'Expires On',
  'common.next_payment': 'Next Payment',
  'common.no_active_subscription': 'No active subscription',
  'common.only_admin_can_change': 'Only Admin can make changes to the subscription',
  'common.save_20_percent': 'Save 20%',
  'common.assigned_to': 'Assigned to:',
  'common.pending': 'Pending',
  'common.unassigned': 'Unassigned',
  'common.places_saved': 'places saved',
  'common.done': 'done',
  'dashboard.todays_menu': "Today's Menu",
  'dashboard.items_to_buy': 'items to buy',
  'dashboard.pending': 'pending',
  'todo.category.supermarket': 'Supermarket',
  'todo.category.wet_market': 'Wet Market',
  'expenses.category.housing_utilities': 'Housing & Utilities',
  'expenses.category.food_daily': 'Food & Daily Needs',
  'expenses.category.transport_travel': 'Transport & Travel',
  'expenses.category.health_personal': 'Health & Personal Care',
  'expenses.category.fun_lifestyle': 'Fun & Lifestyle',
  'expenses.category.miscellaneous': 'Miscellaneous',
  'info.category.home': 'Home',
  'info.category.school': 'School',
  'info.category.doctor': 'Doctor',
  'info.category.hospital': 'Hospital',
  'info.category.shops': 'Shops',
  'info.category.others': 'Others',
};