
import { ShoppingCategory } from './types';

export const EXPENSE_CATEGORIES = [
  'Housing & Utilities',
  'Food & Daily Needs',
  'Transport & Travel',
  'Health & Personal Care',
  'Fun & Lifestyle',
  'Miscellaneous'
];

// Colors based on brand palette: #3EAFD2, #FF9800, #7E57C2, #4CAF50, #F06292, #AB47BC, #757575
export const SHOPPING_CATEGORY_COLORS: Record<ShoppingCategory, string> = {
  [ShoppingCategory.SUPERMARKET]: 'border-l-[#3EAFD2]',
  [ShoppingCategory.WET_MARKET]: 'border-l-[#4CAF50]',
  [ShoppingCategory.OTHERS]: 'border-l-[#757575]',
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: 'Chinese Simplified' },
  { code: 'zh-TW', name: 'Chinese Traditional' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ko', name: 'Korean' },
  { code: 'ja', name: 'Japanese' },
];

// The source of truth for UI strings.
export const BASE_TRANSLATIONS: Record<string, string> = {
  // Dashboard
  'dashboard.greeting.morning': 'Good morning',
  'dashboard.greeting.afternoon': 'Good afternoon',
  'dashboard.greeting.evening': 'Good evening',
  'dashboard.family_board': 'Family Board',
  'dashboard.tap_to_pin': 'Tap to pin a note...',
  'dashboard.type_note': 'Type a note for the family...',
  'dashboard.shopping': 'Shopping',
  'dashboard.items_needed': 'Items needed',
  'dashboard.tasks': 'Tasks',
  'dashboard.todo': 'To-Do',
  'dashboard.meals': 'Meals',
  'dashboard.planned': 'Planned',
  'dashboard.expenses': 'Expenses',
  'dashboard.this_month': 'This Month',
  'dashboard.up_next': 'Up Next',
  'dashboard.view_schedule': 'View Schedule',
  'dashboard.everyone': 'Everyone',
  'dashboard.eating': 'eating',
  'dashboard.language': 'Language',

  // Filters & Common Tabs
  'filter.all': 'All',
  'filter.today': 'Today',
  'filter.overdue': 'Overdue',
  'filter.later': 'Later',
  'filter.general': 'General',

  // Shopping
  'shopping.title': 'Shopping List',
  'shopping.new_item': 'New Item',
  'shopping.item_name': 'Item Name',
  'shopping.unit_placeholder': 'Unit (pkt, kg)',
  'shopping.quick_add': 'Quick Add',
  'shopping.completed': 'Completed',
  'shopping.clear_all': 'Clear All',
  'shopping.no_items': 'No items in list',
  'category.supermarket': 'Supermarket',
  'category.wet_market': 'Wet Market',
  'category.others': 'Others',

  // Tasks
  'tasks.title': 'Tasks',
  'tasks.new_task': 'New Task',
  'tasks.task_name': 'Task Name',
  'tasks.assignees': 'Assignees',
  'tasks.recurrence': 'Does not repeat',
  'tasks.custom_recurrence': 'Custom Recurrence',
  'tasks.repeat_every': 'Repeat every',
  'tasks.repeat_on': 'Repeat on',
  'tasks.ends': 'Ends',
  'tasks.never': 'Never',
  'tasks.on': 'On',
  'tasks.after': 'After',
  'tasks.occurrences': 'occurrences',
  'tasks.once': 'Once',
  'tasks.daily': 'Daily',
  'tasks.weekly': 'Weekly',
  'tasks.monthly': 'Monthly',
  'tasks.yearly': 'Yearly',
  
  // Tasks Empty States
  'tasks.no_tasks_all': 'No tasks created',
  'tasks.no_tasks_today': 'No tasks due today',
  'tasks.no_tasks_overdue': 'No overdue tasks',
  'tasks.no_tasks_later': 'No upcoming tasks',

  // Day Bubbles (Single Letter)
  'day.letter.sun': 'S',
  'day.letter.mon': 'M',
  'day.letter.tue': 'T',
  'day.letter.wed': 'W',
  'day.letter.thu': 'T',
  'day.letter.fri': 'F',
  'day.letter.sat': 'S',
  
  // Day Short (For Recurrence)
  'day.short.sun': 'Sun',
  'day.short.mon': 'Mon',
  'day.short.tue': 'Tue',
  'day.short.wed': 'Wed',
  'day.short.thu': 'Thu',
  'day.short.fri': 'Fri',
  'day.short.sat': 'Sat',

  // Meals
  'meals.title': 'Meals',
  'meals.day_view': 'Day View',
  'meals.week_view': 'Week View',
  'meals.today': 'Today',
  'meals.back_to_week': 'Back to Current Week',
  'meals.plan_meal': 'Plan meal...',
  'meals.add_dish': 'Add dish',
  'meals.the_dish': 'The Dish',
  'meals.whats_for': 'What\'s for',
  'meals.who_eating': 'Who is eating?',
  'meals.add_meal': 'Add Meal',
  'meals.save_changes': 'Save Changes',
  'meals.suggest_ai': 'Suggest with AI',
  'meals.group_all': 'All',
  'meals.group_adults': 'Adults',
  'meals.group_kids': 'Kids',
  'meals.view_day': 'Day',
  'meals.view_week': 'Week',

  // Meal Types
  'meal.type.breakfast': 'Breakfast',
  'meal.type.lunch': 'Lunch',
  'meal.type.dinner': 'Dinner',
  'meal.type.snacks': 'Snack',

  // Meal Audience
  'meals.audience_label': 'This meal is for',
  'meals.audience_all': 'Everyone',
  'meals.audience_adults': 'Adults',
  'meals.audience_kids': 'Kids',

  // Meal RSVP
  'meals.join': 'Join Meal',
  'meals.im_in': "I'm In",
  'meals.im_out': "I'm Out",
  'meals.leave': 'Leave',
  'meals.eating': 'Eating',
  'meals.ill_be_eating': "I'll be eating",
  'meals.no_dish_yet': 'No dish yet',
  'meals.not_for_you': 'Not for you',
  'meals.no_one_yet': 'No one yet',
  'meals.plan_dish': 'Plan Dish',
  'meals.edit_dish': 'Edit dish',
  'meals.add_meal_plan': 'Add Meal Plan',
  'meals.adults_only': 'Adults Only',
  'meals.kids_only': 'Kids Only',
  'meals.tap_to_join': 'Tap to Join',
  'meals.joined': 'Joined',

  // Expenses
  'expenses.title': 'Expenses',
  'expenses.total_month': 'Total this month',
  'expenses.scan_receipt': 'Scan Receipt',
  'expenses.analyzing': 'Analyzing Receipt with AI...',
  'expenses.breakdown': 'Spending Breakdown',

  // Household Info
  'info.title': 'Household Info',
  'info.add_section': 'Add Custom Section',
  'info.edit_info': 'Edit Info',
  'info.new_info': 'New Info',
  'info.category': 'Category',
  'info.title_label': 'Title',
  'info.content_label': 'Content',
  'info.cat.house_rules': 'House Rules',
  'info.placeholder.category': 'General',
  'info.placeholder.title': 'e.g. WiFi Password',
  'info.placeholder.content': 'Enter details...',

  // Profile
  'profile.title': 'Family Profiles',
  'profile.back': 'Back',
  'profile.add_member': 'Add Family Member',
  'profile.edit_profile': 'Edit Profile',
  'profile.logout': 'Log Out',
  'profile.allergies': 'Allergies & Medical',
  'profile.preferences': 'Preferences',
  'profile.none_added': 'None added',
  'profile.change_photo': 'Change Photo',
  'profile.take_photo': 'Take Photo',
  'profile.choose_library': 'Choose from Library',
  'profile.invite_link': 'Invite Link',
  'profile.copy_link': 'Copy Link',
  'profile.copied': 'Copied!',
  'profile.restart_tutorial': 'Restart Tutorial',

  // Onboarding
  'onboarding.welcome': 'Welcome, {name}!',
  'onboarding.step1.desc': 'Let\'s get your home set up. Click \'Got it\' to go to your profile and add your family members.',
  'onboarding.step2.title': 'Grow your Family',
  'onboarding.step2.desc': 'Tap the + button to add your family members.',
  'onboarding.skip': 'Skip',
  'onboarding.got_it': 'Got it',
  'onboarding.add_member': 'Add Family Member',

  // ToDo (unified Shopping + Tasks)
  'todo.title': 'To Do',
  'todo.shopping': 'Shopping',
  'todo.tasks': 'Tasks',
  'todo.suggested': 'Suggested',
  'todo.completed': 'Completed',
  'todo.no_shopping': 'No shopping items yet',
  'todo.no_tasks': 'No tasks yet',
  'todo.add_hint': 'Press Enter to add / tap (+) to set details',
  'todo.category.home_care': 'Home Care',
  'todo.category.family_care': 'Family Care',
  'todo.category.others': 'Others',

  // Nav
  'nav.home': 'Home',
  'nav.todo': 'To Do',
  'nav.meals': 'Meals',
  'nav.cost': 'Expenses',
  'nav.info': 'Info',
  'nav.profile': 'Profile',
  
  // Common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.add': 'Add',
  'common.remove': 'Remove',
  'common.confirm_clear': 'Are you sure you want to clear these items?',
  'common.close': 'Close',
  'common.edit': 'Edit',
  'common.update': 'Update',
  'common.view': 'View',
  'common.start': 'Start',
  'common.all': 'All',
  'common.none': 'None',
  'common.none_listed': 'None listed',
  'common.more': 'more',
  'common.qty': 'Qty',
  'common.unit_pcs': 'pcs',
  'common.unit_kg': 'kg',
  'common.unit_l': 'L',
  'common.eg': 'e.g.',
  'common.eg_milk': 'e.g., Milk',
  'common.eg_clean_bathroom': 'e.g., Clean bathroom',
  'common.eg_wifi_password': 'e.g. WiFi Password',
  'common.where_did_you_spend': 'Where did you spend?',
  'common.store_name': 'Store name',
  'common.enter_details': 'Enter details...',
  'common.add_with_details': 'Add with details',
  'common.sort_by': 'Sort by',
  'common.show_only_mine': 'Show only mine',
  'common.added_date': 'Added Date',
  'common.due_date': 'Due Date',
  'common.newest': 'newest',
  'common.oldest': 'oldest',
  'common.list': 'List',
  'common.summary': 'Summary',
  'common.all_expenses': 'All Expenses',
  'common.total_for_all': 'Total for all expenses',
  'common.total_for_month': 'Total for',
  'common.joined': 'Joined',
  'common.tap_to_join': 'Tap to Join',
  'common.add_allergy': 'Add allergy',
  'common.add_preference': 'Add preference',
  'common.allergy_medical': 'Allergy & Medical',
  'common.settings': 'Settings',
  'common.plan': 'Subscription',
  'common.security': 'Account',
  'common.payment': 'Payment',
  'common.free': 'Free',
  'common.core': 'Core',
  'common.pro': 'Pro',
  'common.monthly': 'Monthly',
  'common.yearly': 'Yearly',
  'common.mo': 'mo',
  'common.yr': 'yr',
  'common.essential_info': 'Essential',
  'common.house_routine': 'House Routine',
  'common.training': 'Training',
  'common.helper': 'Helper',
  'common.helpers': 'helpers',
  'common.past': 'Past',
  'common.home': 'Home',
  'common.school': 'School',
  'common.doctor': 'Doctor',
  'common.hospital': 'Hospital',
  'common.shops': 'Shops',
  'common.others': 'Others',
  'common.house_rules': 'House Rules',
  'common.routine': 'Routine',
  'common.cleaning': 'Cleaning',
  'common.general': 'General',
  'common.category': 'Category',
  'common.title': 'Title',
  'common.content': 'Content',
  'common.does_not_repeat': 'Does not repeat',
  'common.show': 'Show',
  'common.item_name': 'Item Name',
  'common.task_name': 'Task Name',
  'common.unit': 'Unit',
  'common.unit_placeholder': 'pcs, kg, L...',
  'common.added_date_newest': 'Added Date (newest)',
  'common.added_date_oldest': 'Added Date (oldest)',
  'common.due_date_newest': 'Due Date (newest)',
  'common.due_date_oldest': 'Due Date (oldest)',
  'common.my_items_only': 'My Items Only',
  'common.clear_filters': 'Clear Filters',
  'common.reset_to_default': 'Reset to Default',
  'common.name': 'Name',
  'common.enter_name': 'Enter name',
  'common.current_plan': 'Current Plan',
  'common.price': 'Price',
  'common.popular': 'Popular',
  'common.change_plan': 'Change Plan',
  'common.choose_your_plan': 'Choose Your Plan',
  'common.processing': 'Processing...',
  'common.cancel_subscription': 'Cancel Subscription',
  'common.expires_on': 'Expires On',
  'common.next_payment': 'Next Payment',
  'common.no_active_subscription': 'No active subscription',
  'common.only_admin_can_change': 'Only Admin can make changes to the subscription',
  'common.save_20_percent': 'Save 20%',
  'common.assigned_to': 'Assigned to:',
  'common.pending': 'Pending',
  'common.unassigned': 'Unassigned',
  'common.places_saved': 'places saved',
  'common.done': 'done',
  'dashboard.todays_menu': "Today's Menu",
  'dashboard.items_to_buy': 'items to buy',
  'dashboard.pending': 'pending',
  'todo.category.supermarket': 'Supermarket',
  'todo.category.wet_market': 'Wet Market',
  'expenses.category.housing_utilities': 'Housing & Utilities',
  'expenses.category.food_daily': 'Food & Daily Needs',
  'expenses.category.transport_travel': 'Transport & Travel',
  'expenses.category.health_personal': 'Health & Personal Care',
  'expenses.category.fun_lifestyle': 'Fun & Lifestyle',
  'expenses.category.miscellaneous': 'Miscellaneous',
  'info.category.home': 'Home',
  'info.category.school': 'School',
  'info.category.doctor': 'Doctor',
  'info.category.hospital': 'Hospital',
  'info.category.shops': 'Shops',
  'info.category.others': 'Others',
  
  // Profile - Settings & Account
  'profile.invitation_link': 'Invitation Link',
  'profile.share_link_text': 'Share this link with the new member:',
  'profile.resend_invite': 'Resend Invite',
  'profile.manage_account': 'Manage your account',
  'profile.delete_family_member': 'Delete Family Member',
  'profile.name_label': 'Name',
  'profile.role': 'Role',
  'profile.role_admin': 'Admin',
  'profile.role_spouse': 'Spouse',
  'profile.role_helper': 'Helper',
  'profile.role_child': 'Child',
  'profile.role_other': 'Other',
  'profile.profile_information': 'Profile Information',
  'profile.first_name': 'First Name',
  'profile.last_name': 'Last Name',
  'profile.mobile_number': 'Mobile Number',
  'profile.email_password': 'Email & Password',
  'profile.email_address': 'Email Address',
  'profile.email_managed_by_google': 'Email managed by Google account',
  'profile.current_password': 'Current Password',
  'profile.new_password': 'New Password',
  'profile.notifications': 'Notifications',
  'profile.enable_notifications': 'Enable Notifications',
  'profile.delete_account': 'Delete Account',
  'profile.subscription_info': 'Subscription Information',
  'profile.subscription_canceled': 'Subscription Canceled',
  'profile.what_happens_next': 'What happens next?',
  'profile.access_until_end': 'You\'ll continue to have access to premium features until the end of your current billing period.',
  'profile.revert_to_free': 'After that, your account will automatically revert to the free plan.',
  'profile.resubscribe_anytime': 'You can resubscribe at any time from your profile settings.',
  'profile.helper_salary_info': 'Salary Information',
  'profile.helper_start_date': 'Start Date',
  'profile.helper_base_salary': 'Base Salary (HK$/month)',
  'profile.helper_food_allowance': 'Food Allowance (HK$/month)',
  'profile.helper_other_allowances': 'Other Allowances',
  'profile.add_allowance': 'Add Allowance',
  'profile.total_salary': 'Total Monthly Salary',
  'profile.card_holder': 'Card Holder',
  'profile.card_expires': 'Expires',
  'profile.card_number': 'Card Number',
  'profile.expiry': 'Expiry',
  'profile.cardholder_name': 'Cardholder Name',
  'profile.card_type': 'Card Type',
  'profile.save_payment': 'Save Payment Method',

  // Helper Management
  'helper.statutory_holidays': 'Statutory Holidays',
  'helper.working': 'Working?',
  'helper.payslip_confirmation': 'Payslip Confirmation',
  'helper.employer': 'Employer',
  'helper.helper': 'Helper',
  'helper.sign': 'Sign',
  'helper.signed': 'Signed',
  'helper.salary_not_configured': 'Salary details not configured',
  'helper.input_salary': 'Input Salary Details',
  'helper.select_compensation': 'Select Compensation Type',
  'helper.time_in_lieu': 'Time-in-lieu (1 day off)',
  'helper.overtime_pay': 'Overtime Pay',
  'helper.past_holidays': 'Past Holidays',
  'helper.past_payslips': 'Past Payslips',
  'helper.no_helpers': 'No helpers in this household',
  'helper.no_upcoming_holidays': 'No upcoming holidays',
  'helper.no_past_records': 'No past records',
  'helper.no_past_payslips': 'No past payslips',
  'helper.overtime_amount': 'Overtime Pay Amount',
  'helper.amount': 'Amount (HK$)',
  'helper.add_to_payslip_question': "Add this amount to their monthly payslip?",
  'helper.confirm_signature': 'Confirm Signature',
  'helper.sign_warning': "Press to confirm this month's salary. This action CANNOT be reversed.",
  'helper.confirm_sign': 'Confirm & Sign',
  'helper.calculated_amount': 'Calculated Amount',
  'helper.change_amount': 'Change Amount',
  'helper.base_salary': 'Base Salary',
  'helper.food_allowance': 'Food Allowance',
  'helper.other_allowances': 'Other Allowances',
  'helper.overtime': 'Overtime',
  'helper.total': 'Total',
  'helper.new_amount': 'New Total Amount (HK$)',
  'helper.payslip_confirmed': 'Payslip confirmed and locked',
  'helper.manual_amount': 'Manual Amount',
  'helper.amount_overridden': 'Amount has been manually adjusted by Admin',
  'helper.revert_to_calculated': 'Revert to Calculated Amount',
  'common.yes': 'Yes',
  'common.no': 'No',

  // Dashboard
  'dashboard.no_meals_today': 'No meals remaining for today',
  'dashboard.dark_mode': 'Dark Mode (BETA)',
  'dashboard.light_mode': 'Light Mode',

  // Expenses
  'expenses.error': 'Error',
  'expenses.no_data': 'No expense data',
  'expenses.upload_photo': 'Upload Photo',
  'expenses.amount': 'Amount',
  'expenses.select_month': 'Select Month',
  'expenses.add_to_start': 'Add an expense to get started',

  // HouseholdInfo
  'info.no_entries_yet': 'No entries yet',
  'info.no_countries_found': 'No countries found',
  'info.add_contacts_hint': 'Add important contacts and places for your household',
  'info.name_placeholder': 'e.g., City General Hospital',
  'info.address_placeholder': '123 Main St, City',
  'info.note_placeholder': 'Any additional details...',

  // ToDo
  'todo.tap_to_add': 'Tap above to add one',

  // Auth & Loading
  'auth.tidying_up': 'Tidying things up...',
  'auth.please_wait': 'Please wait a moment',
  'auth.setting_up': 'Setting up your account',
  'auth.almost_ready': 'Almost ready',

  // Invite
  'invite.loading': 'Loading invitation...',
  'invite.completing': 'Completing invitation...',

  // Placeholders
  'placeholder.search_country': 'Search country...',
  'placeholder.mobile_number': 'Mobile number',
  'placeholder.mm_yy': 'MM/YY',
  'placeholder.name_on_card': 'Name on card',
  'placeholder.enter_code': 'Enter 6-digit code',
  'placeholder.first_name': 'John',
  'placeholder.last_name': 'Doe',
  'placeholder.enter_password': 'Enter password',
  'placeholder.min_8_chars': 'At least 8 characters',

  // Common - additional
  'common.saving': 'Saving...',
  'common.items': 'items',
  'common.share': 'Share',
  'common.deleting': 'Deleting...',

  // Language & Translation
  'language.ai_disclaimer': 'Translation provided by AI. For accuracy, please refer to the original language version if in doubt.',

  // Meals - additional
  'meals.hungry_no_menu': "Someone's hungry, menu unknown...",

  // Subscription & Payment
  'subscription.payment_success': 'Payment successful! Your subscription is being updated...',
  'subscription.change_plan': 'Change Plan',
  'subscription.choose_plan': 'Choose Your Plan',
  'subscription.admin_only': 'Only Admin can make changes to the subscription',
  'subscription.active_until': 'Your subscription is active until',
  'subscription.canceled_success': 'Your subscription has been successfully canceled.',
  'subscription.confirm_cancel': 'Are you sure you want to cancel your subscription? You will lose access to premium features at the end of your billing period.',

  // Confirmation Dialogs
  'confirm.delete_member': 'Are you sure you want to delete this family member? This action cannot be undone.',
  'confirm.delete_account': 'Are you sure you want to delete your account? This change will be permanent.',
  'confirm.delete_account_final': 'Are you sure you want to delete? After deletion it will be immediate.',
  'confirm.clear_completed': 'Delete all completed items? This action cannot be undone.',
  'confirm.delete_expense': 'Are you sure you want to delete this receipt/expense?',

  // Expenses - additional
  'expenses.add_expense': 'Add Expense',
  'expenses.enter_expense': 'Enter Expense',
  'expenses.confirm_receipt': 'Confirm Receipt',

  // Maps
  'maps.google_not_installed': 'Google Maps is not installed. Open in Apple Maps instead?',

  // Expenses - Form Labels & Buttons
  'expenses.shop_name': 'Shop Name',
  'expenses.date': 'Date',
  'expenses.enter_manually': 'Enter Manually',
  'expenses.or': 'or',
  'expenses.tap_to_zoom': 'Tap to zoom',
  'expenses.no_receipt_image': 'No receipt image',
  'expenses.no_expenses_yet': 'No expenses yet',
  'expenses.no_expenses_month': 'No expenses in',
  'expenses.tap_add_first': 'Tap + to add your first expense',
  'expenses.go_current_month': 'Go to Current Month',
  'expenses.show_all_expenses': 'Show All Expenses',
  'expenses.yes_delete': 'Yes, delete',
  'expenses.in_currency': 'in',

  // Expenses - Image Viewer
  'expenses.double_tap_reset': 'Double tap to reset',
  'expenses.drag_to_pan': 'Drag to pan',
  'expenses.pinch_to_zoom': 'Pinch to zoom',
  'expenses.double_tap_zoom': 'Double tap to zoom',
  'expenses.tap_outside_close': 'Tap outside to close',

  // House Routine Categories
  'routine.category.house_rules': 'House Rules',
  'routine.category.routine': 'Routine',
  'routine.category.meal_preparations': 'Meal Preparations',
  'routine.category.child_care': 'Child Care',
  'routine.category.cleaning': 'Cleaning',
  'routine.category.grocery_market': 'Grocery & Market',
  'routine.category.laundry_wardrobe': 'Laundry & Wardrobe',
  'routine.category.safety_emergency': 'Safety & Emergency',
  'routine.category.energy_bills': 'Energy & Bills',
  'routine.category.helper_self_care': 'Helper Self-Care',
  'routine.category.others': 'Others',

  // HouseholdInfo - Form Labels
  'info.address': 'Address',
  'info.phone_number': 'Phone Number',
  'info.note': 'Note',
  'info.tap_see_more': 'tap to see more',
  'info.add_new_info': 'Add New Info',
  'info.no_routines': 'No routines yet',
  'info.add_routines_hint': 'Add house routines and instructions for your household',
  'info.edit_routine': 'Edit Routine',
  'info.add_routine': 'Add Routine',
  'info.custom_category': 'Custom Category Name',
  'info.custom_category_placeholder': 'Enter custom category',
  'info.routine_name_placeholder': 'e.g., How to make the bed',
  'info.routine_note_placeholder': 'Enter the instructions, steps, or details...',
  'info.no_note': 'No details provided.',

  // ToDo - Form Labels
  'todo.add_item': 'Add item...',
  'todo.add_task': 'Add task...',
  'todo.edit_shopping_item': 'Edit Shopping Item',
  'todo.edit_task': 'Edit Task',
  'todo.add_shopping_item': 'Add Shopping Item',
  'todo.due_date_time': 'Due Date & Time',
  'todo.select_date_time': 'Select date & time',
  'todo.repeat': 'Repeat',
  'todo.assign_to': 'Assign to',
  'todo.clear_all': 'Clear All',
  'todo.you': 'You',

  // ToDo - Recurrence Text
  'recurrence.repeats_every_day': 'Repeats every day',
  'recurrence.every': 'Every',
  'recurrence.weekly': 'Weekly',
  'recurrence.on_the': 'On the',
  'recurrence.of_each_month': 'of each month',
  'recurrence.monthly': 'Monthly',

  // Common - Additional
  'common.you': 'You',
  'common.deleted_user': 'Deleted User',
  'common.add_item': 'Add Item',
  'common.add_task': 'Add Task',
  'common.back': 'Back',

  // Profile - Additional
  'profile.delete_member': 'Delete member',

  // Removed from Household Screen
  'removed.title': 'Removed from Household',
  'removed.subtitle': 'You have been removed from your household',
  'removed.explanation_title': 'What happened?',
  'removed.explanation': 'The household administrator has removed you from the household. Your Helpy account is still active, but you are no longer part of any household.',
  'removed.options_title': 'What would you like to do?',
  'removed.create_new': 'Create a new household',
  'removed.create_new_desc': 'Start fresh with your own household',
  'removed.creating': 'Creating household...',
  'removed.delete_account': 'Delete my account permanently',
  'removed.delete_account_desc': 'Remove all your data from Helpy',
  'removed.delete_confirm_title': 'Delete Account?',
  'removed.delete_confirm_message': 'This action cannot be undone. Your account and all associated data will be permanently deleted.',
  'removed.delete_permanently': 'Delete Permanently',
  'removed.contact_admin': 'If you believe this was done in error, please contact your household administrator.',

  // Meals - Additional
  'meals.meal_type': 'Meal Type',

  // Dashboard - Connection Status
  'dashboard.realtime_active': 'Real-time sync active',
  'dashboard.connecting': 'Connecting...',
  'dashboard.disconnected': 'Disconnected - tap to reconnect',

  // Expenses - Additional
  'expenses.all_expenses': 'All Expenses',
  'expenses.error_invalid_amount': 'Please enter a valid amount',

  // Common - Additional
  'common.na': 'N/A',
  'common.adding': 'Adding...',

  // Error Messages
  'error.add_user': 'Failed to add user. Please try again.',
  'error.generate_invite': 'Failed to generate new invite link',
  'error.select_image': 'Please select an image file',
  'error.image_too_large': 'Image size must be less than 5MB',
  'error.upload_image': 'Failed to upload image. Please try again.',
  'error.cancel_subscription': 'Failed to cancel subscription. Please try again.',
  'error.delete_account_unable': 'Unable to delete account. Please try again.',
  'error.delete_account': 'Failed to delete account. Please try again or contact support.',

  // Settings - Push Notifications
  'settings.push_not_supported': 'Not supported in this browser',
  'settings.push_blocked': 'Blocked - enable in browser settings',
  'settings.push_description': 'Get notified when family adds items',

  // Plan Features - Free
  'plan.feature.free_family': 'Up to 3 family members (incl. admin)',
  'plan.feature.free_helper': '1 Helper',
  'plan.feature.free_expenses': 'Manual expense entry only',
  'plan.feature.free_no_scan': 'No receipt scanning',
  
  // Plan Features - Core
  'plan.feature.core_family': 'Up to 4 family members (incl. admin)',
  'plan.feature.core_helper': '1 Helper',
  'plan.feature.core_expenses': 'All Expense Functions',
  'plan.feature.core_helper_mgmt': 'Helper Management',
  
  // Plan Features - Pro
  'plan.feature.pro_family': 'Up to 8 family members (incl. admin)',
  'plan.feature.pro_helpers': 'Up to 4 Helpers',
  'plan.feature.pro_expenses': 'All Expense Functions',
  'plan.feature.pro_helper_mgmt': 'Helper Management',
  
  // Plan Features - Test (for Stripe testing)
  'plan.feature.test_desc': 'Test plan for payment testing',
  'common.test': 'Test',

  // Household Switch Modal
  'household.already_member': 'Already a Member',
  'household.already_member_of': 'You are already a member of',
  'household.possessive_household': "'s household",
  'household.invited_to_join': "You've been invited to join:",
  'household.switch_to_this': 'Switch to This Household',
  'household.stay_in_current': 'Stay in Current Household',
  'household.only_one_at_time': 'You can only belong to one household at a time',
};